services:

  twenty-db:
    image: postgres:17
    restart: unless-stopped
    container_name: twenty_db
    environment:
      POSTGRES_DB: twenty
      POSTGRES_USER: twenty
      POSTGRES_PASSWORD: twenty
    volumes:
      - /data/crm/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twenty -d twenty"]
      interval: 5s
      timeout: 5s
      retries: 10

  twenty-redis:
    image: redis
    restart: unless-stopped
    container_name: twenty_redis
    command: ["--maxmemory-policy", "noeviction"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  twenty-server:
    image: twentycrm/twenty:latest
    restart: unless-stopped
    container_name: twenty_server
    ports:
      - "3000:3000"
    depends_on:
      twenty-db:
        condition: service_healthy
      twenty-redis:
        condition: service_healthy
    environment:
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://twenty:twenty@twenty-db:5432/twenty
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: redis://twenty-redis:6379
      STORAGE_TYPE: local
      APP_SECRET: ${APP_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      SIGN_UP_ENABLED: "true"
    volumes:
      - /data/crm/server-storage:/app/packages/twenty-server/.local-storage
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/healthz"]
      interval: 5s
      timeout: 5s
      retries: 20

  twenty-worker:
    image: twentycrm/twenty:latest
    restart: unless-stopped
    container_name: twenty_worker
    command: ["yarn", "worker:prod"]
    depends_on:
      twenty-db:
        condition: service_healthy
      twenty-server:
        condition: service_healthy
    environment:
      PG_DATABASE_URL: postgres://twenty:twenty@twenty-db:5432/twenty
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: redis://twenty-redis:6379
      STORAGE_TYPE: local
      APP_SECRET: ${APP_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DISABLE_DB_MIGRATIONS: "true"
      DISABLE_CRON_JOBS_REGISTRATION: "true"
    volumes:
      - /data/crm/server-storage:/app/packages/twenty-server/.local-storage
